### ISSUE TITLE
No margins for content

### ISSUE THREAD

**Issue by stratofax** [cadentcom/pico-wp-block-theme#17]
No margins for content. There needs to be a content div to contain all the content in the page so we can adjust the margins with CSS.

Here's a sample content column:

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Full-Page Column Layout</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <div class="content-column">
        <h1>Welcome to My Website</h1>
        <p>This is a sample paragraph to demonstrate a full-page column layout. You can add more content here like text, images, and other elements.</p>
        <!-- More content can be added here -->
    </div>
</body>
</html>
```

And here's the corresponding CSS:

```css
body, html {
    margin: 0;
    padding: 0;
    height: 100%;
}

.content-column {
    margin: 20px; /* Sets the margin around the column */
    padding: 20px; /* Sets the padding inside the column */
    height: calc(100% - 40px); /* Adjusts the height to take the margin into account */
    box-sizing: border-box; /* Ensures padding does not add to the total width and height */
}

/* Additional styling for demonstration */
h1, p {
    margin: 0 0 20px 0; /* Adds some spacing below each element */
}

p:last-child {
    margin-bottom: 0; /* Removes the bottom margin from the last paragraph */
}

```
